extend type Query {
  adminActiveRoomStats(
    minMemberCount: Int
    activityWindowMinutes: Int
  ): AdminActiveRoomStats
  adminRoomActivityStats(
    from: DateTime!
    to: DateTime!
  ): AdminRoomActivityStats!
  adminRoomStats: AdminRoomStats
  adminUserStats: AdminUserStats
  adminAnnouncementStats: AdminAnnouncementStats
  adminQnaStats: AdminQnaStats
}

type AdminUserStats {
  totalCount: Int!
  verifiedCount: Int!
  pendingCount: Int!
}

type AdminRoomStats {
  totalCount: Int!
  membershipCount: Int!
  activeRoomCount: Int!
  managingUserCount: Int!
  participantCount: Int!
}

type AdminRoomActivityStats {
  managingUserCount: Int!
  participantCount: Int!
  roomCount: Int!
}

type AdminActiveRoomStats {
  count: Int!
  minMemberCount: Int!
  activityWindowMinutes: Int!
}

type AdminAnnouncementStats {
  totalCount: Int!
}

type AdminQnaStats {
  postCount: Int!
}
