services:
  couchdb:
    image: $IMAGE_NAMESPACE/${IMAGE_DEPENDENCY_PREFIX}couchdb:$COUCHDB_TAG
    restart: $RESTART_MODE
    environment:
      COUCHDB_USER: arsnova
      COUCHDB_PASSWORD: arsnova
    volumes:
      - couchdb_data:/opt/couchdb/data
  postgresql-authz:
    image: postgres:14.18-alpine
    restart: $RESTART_MODE
    environment:
      POSTGRES_DB: arsnovaauth
      POSTGRES_USER: arsnovaauth
      POSTGRES_PASSWORD: arsnovaauth
    volumes:
      - postgresql_data_auth:/var/lib/postgresql/data
  postgresql-comments:
    image: postgres:14.18-alpine
    restart: $RESTART_MODE
    environment:
      POSTGRES_DB: arsnovacomment
      POSTGRES_USER: arsnovacomment
      POSTGRES_PASSWORD: arsnovacomment
    volumes:
      - postgresql_data_comment:/var/lib/postgresql/data
  rabbitmq:
    image: $IMAGE_NAMESPACE/${IMAGE_DEPENDENCY_PREFIX}rabbitmq-stomp:$RABBITMQ_TAG
    restart: $RESTART_MODE
    environment:
      RABBITMQ_NODENAME: rabbit@localhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  arsnova-server-core:
    image: $IMAGE_NAMESPACE/${IMAGE_SERVER_PREFIX}core:$CORE_TAG
    restart: $RESTART_MODE
    depends_on:
      - couchdb
      - rabbitmq
    environment:
      SYSTEM_API_PROXYPATH: /api
      SYSTEM_COUCHDB_HOST: couchdb
      SYSTEM_COUCHDB_USERNAME: arsnova
      SYSTEM_COUCHDB_PASSWORD: arsnova
      SYSTEM_COUCHDB_CREATEDB: "true"
      SYSTEM_COUCHDB_MIGRATION_ENABLED: "true"
      SYSTEM_COUCHDB_MIGRATION_HOST: couchdb-import
      SYSTEM_COUCHDB_MIGRATION_USERNAME: arsnova
      SYSTEM_COUCHDB_MIGRATION_PASSWORD: arsnova
      SYSTEM_MESSAGE_BROKER_RABBITMQ_ENABLED: "true"
      SYSTEM_MESSAGE_BROKER_RABBITMQ_HOST: rabbitmq
      SYSTEM_MESSAGE_BROKER_RABBITMQ_USERNAME: guest
      SYSTEM_MESSAGE_BROKER_RABBITMQ_PASSWORD: guest
      SYSTEM_MESSAGE_BROKER_RABBITMQ_VIRTUAL_HOST: /
      SYSTEM_MAIL_LOCALHOST: $ARSNOVA_HOSTNAME
      SYSTEM_FORMATTING_SERVICE_HOST_URL: http://arsnova-server-formatting:3000
      SECURITY_JWT_SECRET: $JWT_SECRET
      SECURITY_JWT_SERVER_ID: arsnova.backend.v3:$JWT_DOMAIN
  arsnova-server-gateway:
    image: $IMAGE_NAMESPACE/${IMAGE_SERVER_PREFIX}gateway:$GATEWAY_TAG
    restart: $RESTART_MODE
    depends_on:
      - rabbitmq
      - arsnova-server-authz
    environment:
      SERVER_PORT: 8080
      ROUTING_ENDPOINTS_CORE: http://arsnova-server-core:8080
      ROUTING_ENDPOINTS_WS_GATEWAY: http://arsnova-server-websocket:8080
      ROUTING_ENDPOINTS_COMMENT_SERVICE: http://arsnova-server-comments:8080
      ROUTING_ENDPOINTS_ROOMACCESS_SERVICE: http://arsnova-server-authz:8080
      ROUTING_ENDPOINTS_FORMATTING_SERVICE: http://arsnova-server-formatting:3000
      HTTP_CLIENT_AUTH_SERVICE: http://arsnova-server-authz:8080
      HTTP_CLIENT_CORE: http://arsnova-server-core:8080
      HTTP_CLIENT_WS_GATEWAY: http://arsnova-server-websocket:8080
      HTTP_CLIENT_COMMENT_SERVICE: http://arsnova-server-comments:8080
      SECURITY_JWT_PUBLIC_SECRET: $JWT_SECRET
      SECURITY_JWT_INTERNAL_SECRET: $JWT_SECRET
      SECURITY_JWT_SERVER_ID: arsnova.backend.v3:$JWT_DOMAIN
  arsnova-server-websocket:
    image: $IMAGE_NAMESPACE/${IMAGE_SERVER_PREFIX}websocket:$WEBSOCKET_TAG
    restart: $RESTART_MODE
    depends_on:
      - rabbitmq
      - arsnova-server-authz
    environment:
      SERVER_PORT: 8080
      STOMP_RELAY_HOST: rabbitmq
      STOMP_RELAY_USER: guest
      STOMP_RELAY_PASSWORD: guest
      HTTP_CLIENT_AUTH_SERVICE: http://arsnova-server-authz:8080
      SECURITY_JWT_SECRET: $JWT_SECRET
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
  arsnova-server-authz:
    image: $IMAGE_NAMESPACE/${IMAGE_SERVER_PREFIX}authz:$AUTHZ_TAG
    restart: $RESTART_MODE
    depends_on:
      - postgresql-authz
      - rabbitmq
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-authz:5432/arsnovaauth
      SPRING_DATASOURCE_USERNAME: arsnovaauth
      SPRING_DATASOURCE_PASSWORD: arsnovaauth
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest
      SECURITY_JWT_SECRET: $JWT_SECRET
      SECURITY_JWT_SERVER_ID: arsnova.backend.v3:$JWT_DOMAIN
  arsnova-server-comments:
    image: $IMAGE_NAMESPACE/${IMAGE_SERVER_PREFIX}comments:$COMMENTS_TAG
    restart: $RESTART_MODE
    depends_on:
      - postgresql-comments
      - rabbitmq
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-comments:5432/arsnovacomment
      SPRING_DATASOURCE_USERNAME: arsnovacomment
      SPRING_DATASOURCE_PASSWORD: arsnovacomment
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      SECURITY_JWT_SECRET: $JWT_SECRET
  arsnova-webclient:
    image: $IMAGE_NAMESPACE/arsnova-webclient:$WEBCLIENT_TAG
    restart: $RESTART_MODE
  arsnova-server-formatting:
    image: $IMAGE_NAMESPACE/${IMAGE_SERVER_PREFIX}formatting:$FORMATTING_TAG
    restart: $RESTART_MODE
    environment:
      SERVER_PORT: 3000
  arsnova-proxy:
    image: $IMAGE_NAMESPACE/${IMAGE_DEPENDENCY_PREFIX}arsnova-proxy:$PROXY_TAG
    restart: $RESTART_MODE
    depends_on:
      - arsnova-server-core
      - arsnova-server-authz
      - arsnova-server-websocket
      - arsnova-server-gateway
      - arsnova-server-comments
      - arsnova-webclient
    environment:
      ARSNOVA_HOSTNAME: $ARSNOVA_HOSTNAME
      CSP_FRAME_ANCESTORS: $CSP_FRAME_ANCESTORS

volumes:
  couchdb_data:
  postgresql_data_auth:
  postgresql_data_comment:
  rabbitmq_data:
