= Particify Docker Orchestration

This repository contains files to integrate all of the Particify services and service dependencies using Docker:

* Configuration for Docker Compose
* Dockerfiles (and additional assets) to create modified versions of thirdparty images

== Requirements

=== Hardware

* CPU: 4 Cores or vCPU
* RAM: 8 GiB
* Storage: 10 GiB for Docker images and containers, additional storage for volumes containing user data depends on usage

=== Software

* Linux is the recommended OS, but basically any OS that is supported by Docker Engine and runs shell scripts should work.
* https://docs.docker.com/engine/install/[Docker Engine] >= 20.10 (older versions might work but are not tested for compatibility)
* https://docs.docker.com/compose/install/[Docker Compose]

== Usage

=== Preparations

. Clone this repository.
. Inside the repositories root directory run `./set-env.sh <env>`. env can be `prod` or `dev`.

=== Running

. Run `PORT=<port> docker-compose up`. Append `-d` to run in detached mode for production.
. Run `docker-compose down` stop and remove the containers.
. Run `docker-compose pull` to update the images.

=== Configuration

The default configuration can be adjusted via environment variables:

|=======
|Variable |Default value |Description
|PORT |80 |Port used for the frontend proxy
|JWT_SECRET |secret |Encryption token for authentication (MUST be changed for production)
|JWT_DOMAIN |example.com |A domain usable as server ID (used for the JWT issuer/audience claim)
|ARSNOVA_HOSTNAME |app.particify.de |Hostname for the application
|CORE_TAG |3.4.20210824 |Docker tag (repository branch) for Core Backend
|WSGW_TAG |3.4.20210724 |Docker tag (repository branch) for WebSocket Gateway
|HTTPGW_TAG |3.4.20210730 |Docker tag (repository branch) for HTTP Gateway
|AUTH_TAG |3.4.20210730 |Docker tag (repository branch) for Auth Service
|COMMENT_TAG |3.4.20210806 |Docker tag (repository branch) for Comment Service
|WEB_TAG |3.4.20210812 |Docker tag (repository branch) for Webclient
|FORMATTING_TAG|3 |Docker tag (repository branch) for Formatting Service
|=======

Example: `PORT=8100 WEB_TAG=my-dev-branch docker-compose up`

NOTE: Docker images are not automatically created for development branches.
Make sure to trigger the `docker_image_dev` job in GitLab's pipeline view and delete the image from the registry once it is no longer needed.

=== PostgreSQL updates

When the PostgreSQL image was updated to a new major version, `pg_upgrade.sh` needs to be run to perform a database migration.
The script expects the service name, the old and the new PostgreSQL version as parameters.
There is no rollback support, so backups for the PostgreSQL volumes should be created before running the script.
