= Particify Docker Orchestration

This repository contains files to integrate all of the Particify services and service dependencies using Docker:

* Configuration for Docker Compose
* Dockerfiles (and additional assets) to create modified versions of thirdparty images

== Usage

=== Preparations

. Create a GitLab
  https://gitlab.com/profile/personal_access_tokens[Personal Access Token]
  with `read_registry` scope.
. Authenticate the Docker environment with the GitLab registry:
  `docker login registry.gitlab.com`
. Clone this repository.
. Inside the repositories root directory run `./set-env.sh <env>`. env can be `prod` or `dev`.

=== Running

. Run `PORT=<port> docker-compose up`. Append `-d` to run in detached mode for production.
. Run `docker-compose down` stop and remove the containers.
. Run `docker-compose pull` to update the images.

=== Configuration

The default configuration can be adjusted via environment variables:

|=======
|Variable |Default value |Description
|PORT |80 |Port used for the frontend proxy
|ARSNOVA_HOSTNAME |app.particify.de |Hostname for the application
|CORE_TAG |master |Docker tag (repository branch) for Core Backend
|WSGW_TAG |master |Docker tag (repository branch) for WebSocket Gateway
|HTTPGW_TAG |master |Docker tag (repository branch) for HTTP Gateway
|AUTH_TAG |master |Docker tag (repository branch) for Auth Service
|COMMENT_TAG |master |Docker tag (repository branch) for Comment Service
|WEB_TAG |master |Docker tag (repository branch) for Webclient
|WEB_LEGACY_TAG |master |Docker tag (repository branch) for Webclient (legacy)
|=======

Example: `PORT=8100 WEB_TAG=my-dev-branch docker-compose up`

NOTE: Docker images are not automatically created for development branches.
Make sure to trigger the `docker_image_dev` job in GitLab's pipeline view and delete the image from the registry once it is no longer needed.
