services:
  apisix:
    image: apache/apisix:3.18.0-debian@sha256:84e6b5e787e9f889ebff88161cb9a16599bafcffa236c6b54c7f779a0655940d
    ports:
      - 9080:9080
    volumes:
      - $ROOT_DIR/.docker/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - $ROOT_DIR/.docker/apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    extra_hosts:
      - host.containers.internal:host-gateway
