services:
  apisix:
    image: apache/apisix:3.16.0-debian@sha256:b921bdef3cfb2ca72e483d643f40e7843683ff8e188984489c2020f17654ee88
    ports:
      - 9080:9080
    volumes:
      - $ROOT_DIR/.docker/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - $ROOT_DIR/.docker/apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml:ro
    extra_hosts:
      - host.containers.internal:host-gateway
