services:
  postgresql-core4:
    image: postgres:17.5-alpine
    restart: $RESTART_MODE
    environment:
      POSTGRES_DB: arsnova
      POSTGRES_USER: arsnova
      POSTGRES_PASSWORD: arsnova
    volumes:
      - core-postgresql-data:/var/lib/postgresql/data
  arsnova-server-core4:
    image: $IMAGE_NAMESPACE/${IMAGE_SERVER_PREFIX}core4:$CORE_TAG
    restart: $RESTART_MODE
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-core4:5432/arsnova
      SPRING_DATASOURCE_USERNAME: arsnova
      SPRING_DATASOURCE_PASSWORD: arsnova
      SECURITY_JWT_SECRET: $JWT_SECRET
      SECURITY_JWT_ISSUER: arsnova.backend.v3:$JWT_DOMAIN
  arsnova-server-core:
    environment:
      SYSTEM_EXTERNAL_USER_MANAGEMENT: "true"
      SYSTEM_EXTERNAL_ROOM_MANAGEMENT: "true"
  arsnova-server-websocket:
    environment:
      SYSTEM_EXTERNAL_USER_MANAGEMENT: "true"
      SECURITY_AUTHORIZE_URI_ENDPOINT: "/api/jwt"
      HTTP_CLIENT_AUTH_SERVICE: "http://arsnova-server-core4:8080"

volumes:
  core-postgresql-data:
