services:
  postgresql-core4:
    image: postgres:18.1-alpine@sha256:4eb15de8e7b692c02427a2df278d18eb89422a534e428efb6d43c968250334d4
    restart: $RESTART_MODE
    environment:
      POSTGRES_DB: arsnova
      POSTGRES_USER: arsnova
      POSTGRES_PASSWORD: arsnova
    volumes:
      - core-postgresql-data:/var/lib/postgresql
  arsnova-server-core4:
    image: $IMAGE_NAMESPACE/${IMAGE_SERVER_PREFIX}core4:$CORE_TAG
    restart: $RESTART_MODE
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql-core4:5432/arsnova
      SPRING_DATASOURCE_USERNAME: arsnova
      SPRING_DATASOURCE_PASSWORD: arsnova
      SECURITY_JWT_SECRET: $JWT_SECRET
      SECURITY_JWT_ISSUER: arsnova.backend.v3:$JWT_DOMAIN
  arsnova-server-core:
    environment:
      SYSTEM_EXTERNAL_DATA_MANAGEMENT: "true"
  arsnova-server-websocket:
    environment:
      SYSTEM_EXTERNAL_USER_MANAGEMENT: "true"
      SECURITY_AUTHORIZE_URI_ENDPOINT: "/api/jwt"
      HTTP_CLIENT_AUTH_SERVICE: "http://arsnova-server-core4:8080"

volumes:
  core-postgresql-data:
