services:
  mailpit:
    image: axllent/mailpit:v1.30@sha256:d5ecbb067db3705fa953d79e1b7f81ef84038df67aba6c52825d8c02a1ea748a
    ports:
      - 127.0.0.1:8025:8025
    volumes:
      - mailpit-data:/data

volumes:
  mailpit-data:
