services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.8@sha256:b0f60d489d51c5d113390bdf5461d4c06e6051be026c05549f2e1e10ec352bcc
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql-keycloak/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - $ROOT_DIR/.docker/keycloak/import:/opt/keycloak/data/import
  postgresql-keycloak:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:2426484c3efdd6b7d67fe9e111017a4a1722367340197465de8fb2167238f2e2
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-postgresql-data:/var/lib/postgresql/data

volumes:
  keycloak-postgresql-data:
