services:
  postgresql-core4:
    image: pgautoupgrade/pgautoupgrade:18-alpine
  arsnova-server-core4:
    image: devcontainer-arsnova-server-core4:$CORE4_TAG
    init: true
    build:
      context: $ROOT_DIR/core4/.devcontainer
      args:
        APP_IMAGE: registry.gitlab.com/particify/dev/foss/arsnova-server/core4:$CORE4_TAG
        INSTALL_MAVEN: "true"
        MAVEN_VERSION: $MAVEN_VERSION
    environment:
      DEBUG_HOST: 0.0.0.0
      DEBUG_PORT: $CORE4_DEBUG_PORT
      SERVER_PORT: ""
      SPRING_PROFILES_ACTIVE: dev
      SPRING_APPLICATION_JSON: '{"server": {"port": "8080"}}'
      SECURITY_SAML2_CREDENTIALSPATH: file:/app/credentials
      GRADLE_RO_DEP_CACHE: /home/dev/.gradle-ro-dep-cache
    ports:
      - $CORE4_DEBUG_PORT:$CORE4_DEBUG_PORT
    volumes:
      - $ROOT_DIR:/workspace
      - $ROOT_DIR/core4/credentials:/app/credentials
      - gradle-workspace-core4:/workspace/.gradle
      - gradle-cache-core4:/home/dev/.gradle/caches
      - gradle-ro-dep-cache:/home/dev/.gradle-ro-dep-cache:ro
      - gradle-wrapper:/home/dev/.gradle/wrapper
      - vscode-extensions-core4:/home/dev/.vscode-server/extensions

volumes:
  gradle-cache-core4:
  gradle-workspace-core4:
  vscode-extensions-core4:
