services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.6@sha256:dea26401d06341095cc4ea9d66896200b55de5ca1daa1d2fcbe58493afa6e0ad
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgresql-keycloak/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    volumes:
      - $ROOT_DIR/.docker/keycloak/import:/opt/keycloak/data/import
  postgresql-keycloak:
    image: pgautoupgrade/pgautoupgrade:18-alpine@sha256:669ced02f31161f6bda9b15b83bd7fca2de619fbd2b91af1fb4a3e0c8e3da2ca
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-postgresql-data:/var/lib/postgresql/data

volumes:
  keycloak-postgresql-data:
