#!/bin/bash
PATH=$HOME/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/cli-bin/:$PATH
COMMAND=$1
PROJECT=$2

if ! command -v git &> /dev/null; then
  echo ERROR: Git is not installed.
  exit 1
fi

if ! command -v docker &> /dev/null; then
  echo ERROR: Docker Engine is not installed.
  echo
  echo https://docs.docker.com/engine/install/
  exit 1
fi

if ! docker compose &> /dev/null; then
  echo ERROR: Docker Compose v2 is not installed.
  echo
  echo https://docs.docker.com/compose/install/compose-plugin/
  echo
  echo On Debian-based systems:
  echo apt install docker-compose-plugin
  exit 1
fi

if command docker-compose &> /dev/null && docker-compose --version | grep "docker-compose version" &> /dev/null; then
  echo ERROR: Legacy Docker Compose v1 is installed.
  echo
  echo Please remove this version to avoid issues.
  exit 1
fi

if ! command -v code &> /dev/null; then
  echo ERROR: Visual Studio Code is not installed.
  echo
  echo https://code.visualstudio.com
  exit 1
fi

if ! code --list-extensions | grep ms-vscode-remote.remote-containers &> /dev/null; then
  code --install-extension ms-vscode-remote.remote-containers
fi

ENV_FILES=""
BASE_COMPOSE_FILE_ARGS=""
while read config_name; do
  if [ -f "docker-orchestration/$config_name.env" ]; then
    ENV_FILES="$ENV_FILES docker-orchestration/$config_name.env"
  fi
  BASE_COMPOSE_FILE_ARGS="$BASE_COMPOSE_FILE_ARGS -f docker-orchestration/$config_name.compose.yaml"
done <config-list
COMPOSE_FILE_ARGS=$BASE_COMPOSE_FILE_ARGS
while read config_name; do
  if [ -f "$config_name.env" ]; then
    ENV_FILES="$ENV_FILES $config_name.env"
  fi
  COMPOSE_FILE_ARGS="$COMPOSE_FILE_ARGS -f devcontainer.$config_name.compose.yaml"
done <config-list

case $COMMAND in
  update|u)
    echo Updating Git repository...
    git submodule update --init --recursive
    $0 update-config
    echo Updating base images for Devcontainers...
    docker compose --project-directory `dirname $0` \
      $BASE_COMPOSE_FILE_ARGS \
      pull
    $0 build
    ;;
  update-config)
    echo Updating configuration for Docker Compose...
    if [ ! -f local.env ]; then
      echo "# Custom environment configuration overrides" > local.env
    fi
    if [ ! -f local.compose.yaml ]; then
      echo -e "# Custom Docker Compose configuration overrides\nservices: {}" > local.compose.yaml
    fi
    echo "# GENERATED - DO NOT EDIT - RUN $0 $1 TO UPDATE" > .env
    cat $ENV_FILES devcontainer.env | grep -v ^# | tac | awk -F "=" '!a[$1]++' | tac >> .env
    echo "# GENERATED - DO NOT EDIT - RUN $0 $1 TO UPDATE" > .compose.yaml
    docker compose --project-directory `dirname $0` \
      $COMPOSE_FILE_ARGS \
      -f local.compose.yaml \
      config >> .compose.yaml
    ;;
  open|o)
    if [ -d "$PROJECT" ]; then
      devcontainer open "$PROJECT"
    else
      echo ERROR: Invalid project
      exit 1
    fi
    ;;
  run|r)
    if [ ! -f .compose.yaml ]; then
      $0 update-config
    fi
    echo Starting Devcontainers...
    shift 1
    docker compose -f .compose.yaml up $@
    ;;
  build|b)
    if [ ! -f .compose.yaml ]; then
      $0 update-config
    fi
    echo Building Devcontainers...
    docker compose -f .compose.yaml build
    ;;
  logs|l)
    if [ ! -f .compose.yaml ]; then
      $0 update-config
    fi
    shift 1
    docker compose -f .compose.yaml logs $@
    ;;
  compose|c)
    if [ ! -f .compose.yaml ]; then
      $0 update-config
    fi
    shift 1
    docker compose -f .compose.yaml $@
    ;;
  *)
    echo Usage:
    echo "    $0 update           Update Git repositories, Docker Compose configuration and Devcontainers"
    echo "    $0 update-config    Update the configuration for Docker Compose"
    echo "    $0 open <project>   Open project in Devcontainer with Visual Studio Code"
    echo "    $0 run              Start Devcontainers for all services"
    echo "    $0 build            (Re-)build Devcontainers"
    echo "    $0 logs             Show logs or the log for a specific service"
    echo "    $0 compose          Execute a Docker Compose command"
    ;;
esac
