workflow:
  name: core4

include: .gitlab/ci/gradle.yml

spotbugs:
  rules:
    - when: never

ktlint:
  rules:
    - when: never

spotless:
  extends: .gradle
  stage: test
  needs:
    - compile
  script:
    # git fetch is needed for Spotless' ratchetFrom
    - git fetch origin master
    - ../gradlew $GRADLE_CLI_OPTS spotlessKotlinApply spotlessKotlinGradleApply -x classes -x processAot -x processTestAot

detekt:
  extends: .gradle
  stage: test
  needs:
    - compile
  script:
    - ../gradlew $GRADLE_CLI_OPTS detekt -x classes

unit_test:
  image: registry.gitlab.com/particify/dev/foss/arsnova-server/openjdk-podman:25
  variables:
    TESTCONTAINERS_RYUK_CONTAINER_PRIVILEGED: "false"
  before_script:
    - date
    - echo "$PROJECT"
    - cd "$PROJECT"
    - export DOCKER_HOST=unix:///tmp/podman.sock
    - mkdir -p build/reports
    - podman system service --time=0 "$DOCKER_HOST" > build/reports/podman-service.log 2>&1 &
    - sleep 1
  script:
    - ../gradlew $GRADLE_CLI_OPTS test jacocoTestReport -x classes -x processAot -x processTestAot
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print "Instructions covered:", covered, "/", instructions; print "Code coverage:", 100 * covered / instructions "%" }' build/reports/jacoco/test/jacocoTestReport.csv

docker_image:
  variables:
    GRADLE_JIB_OPTS: -x processAot -x processTestAot
