FROM quay.io/podman/stable:v5.8.7-immutable@sha256:f345d8d4fddea244d3a1ced27bcec82d14cc9e32cb5ead7f5882b0baf59dc8b0

RUN \
  mkdir -p /etc/containers/containers.conf.d && \
  printf '[containers]\nnetns="pasta"\n' > /etc/containers/containers.conf.d/50-netns-pasta.conf && \
  mkdir -p /home/podman/.config/containers && \
  printf '[storage]\ndriver = "overlay"\n\n[storage.options]\nadditionalimagestores = ["/var/lib/shared"]\n' \
    > /home/podman/.config/containers/storage.conf && \
  chown -R podman:podman /home/podman/.config
RUN dnf -y install java-25-openjdk-devel && dnf -y clean all
USER podman
ENV JAVA_HOME=/usr/lib/jvm/java-25-openjdk
