arsnova:
  alias-words:
    nouns:
      - alpaca
      - ant
      - armadillo
      - badger
      - barracuda
      - bat
      - bear
      - beaver
      - bee
      - beetle
      - bison
      - bumblebee
      - butterfly
      - cockatoo
      - chameleon
      - cheetah
      - crocodile
      - deer
      - dolphin
      - donkey
      - dragonfly
      - duck
      - eagle
      - emu
      - elephant
      - falcon
      - ferret
      - flamingo
      - fox
      - giraffe
      - goat
      - goose
      - gorilla
      - guinea-pig
      - hare
      - hedgehog
      - heron
      - hippo
      - hornet
      - hummingbird
      - ibex
      - iguana
      - jaguar
      - jellyfish
      - kangaroo
      - kiwi
      - koala
      - leopard
      - lion
      - lemur
      - llama
      - lobster
      - lynx
      - meerkat
      - mole
      - monkey
      - narwhal
      - octopus
      - orca
      - owl
      - panda
      - peacock
      - pelican
      - penguin
      - pig
      - pigeon
      - piranha
      - polar-bear
      - puma
      - rabbit
      - racoon
      - rhino
      - salamander
      - seal
      - shark
      - sheep
      - squirrel
      - starfish
      - stork
      - swan
      - tapir
      - tiger
      - turtle
      - viper
      - wolf
      - wombat
      - woodpecker
      - zebra
    special-nouns:
      - mammoth
      - archaeopteryx
      - brachiosaurus
      - brontosaurus
      - pteranodon
      - stegosaurus
      - triceratops
      - tyrannosaurus
      - velociraptor
      - dragon
      - unicorn
      - vampire
      - werewolf
    adjectives:
      - adept
      - adventurous
      - ambitious
      - brilliant
      - brave
      - capable
      - chatty
      - cheerful
      - courageous
      - creative
      - colorful
      - curious
      - determined
      - diligent
      - elegant
      - enthusiastic
      - fabulous
      - focused
      - funny
      - generous
      - giant
      - helpful
      - happy
      - hilarious
      - imaginative
      - ingenious
      - inquisitive
      - insightful
      - inventive
      - knowledgeable
      - observant
      - optimistic
      - passionate
      - patient
      - persistent
      - reliable
      - resourceful
      - sincere
      - smart
      - swift
      - thoughtful
      - tiny
      - unique
      - versatile
      - vivid
