variables:
  OUTPUT_DIR: target
  WAR_FILE: $OUTPUT_DIR/arsnova-backend-*.war

stages:
  - build
  - test
  - package
  - deploy

.maven:
  image: maven:3-jdk-8
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --fail-at-end --show-version"
  cache:
    key: maven-repository-2.x
    paths:
      - .m2/repository

compile:
  extends: .maven
  stage: build
  artifacts:
    paths:
      - $OUTPUT_DIR
  script:
    - mvn $MAVEN_CLI_OPTS test-compile

checkstyle:
  extends: .maven
  stage: test
  needs: []
  allow_failure: true
  script:
    - mvn $MAVEN_CLI_OPTS checkstyle:check -Dcheckstyle.missing-javadoc.severity=info

unit_test:
  extends: .maven
  stage: test
  needs:
    - compile
  artifacts:
    paths:
      - $OUTPUT_DIR
    reports:
      junit: $OUTPUT_DIR/surefire-reports/TEST-*.xml
  coverage: '/Code coverage: \d+\.\d+/'
  script:
    - mvn $MAVEN_CLI_OPTS jacoco:prepare-agent surefire:test jacoco:report
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print "Instructions covered:", covered, "/", instructions; print "Code coverage:", 100 * covered / instructions "%" }' "$OUTPUT_DIR/site/jacoco/jacoco.csv"

package:
  extends: .maven
  stage: package
  needs:
    - compile
  artifacts:
    name: package
    paths:
      - $WAR_FILE
  script:
    - mvn $MAVEN_CLI_OPTS war:war
